// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import CalcController from "./calc_controller"
application.register("calc", CalcController)

import ProctorController from "./proctor_controller"
application.register("proctor", ProctorController)